<a href="https://colab.research.google.com/github/sjkim25/Introduction-to-Artificial-Intelligence/blob/main/week13/Spam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#라이브러리 import
import numpy as np
from tensorflow.keras.layers import Embedding, Flatten, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
#test 문서와 정답 레이블 정의
docs = ['additional income',
        'best price',
        'big bucks',
        'cash bonus',
        'earn extra cash',
        'spring savings certificate',
        'valero gas marketing',
        'all domestic employees',
        'nominations for oct',
        'confirmation from spinner']

labels = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [ ]:
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[5, 14], [13, 17], [37, 10], [47, 8], [21, 38, 47], [14, 32, 15], [48, 1, 14], [44, 20, 27], [18, 20, 8], [37, 33, 14]]


In [ ]:
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[ 5 14  0  0]
 [13 17  0  0]
 [37 10  0  0]
 [47  8  0  0]
 [21 38 47  0]
 [14 32 15  0]
 [48  1 14  0]
 [44 20 27  0]
 [18 20  8  0]
 [37 33 14  0]]


In [ ]:
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.fit(padded_docs, labels, epochs=50, verbose=0)

loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('정확도 = ', accuracy)

정확도 =  1.0


In [ ]:
test_doc = ['big income']
encoded_docs = [one_hot(d, vocab_size) for d in test_doc]
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')

print(model.predict(padded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step
[[0.5367553]]
