<a href="https://colab.research.google.com/github/sjkim25/Introduction-to-Artificial-Intelligence/blob/main/week3/Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Iris Classification / Regression (LR, DT, RF, KNN)**

In [50]:
import pandas as pd
import numpy as np

In [51]:
#data load
from sklearn import datasets
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [52]:
# X_clf -> Sepal Length, Sepal Width, Petal Length, Petal Width. (iris.data를 통해 이미 저장되어있음)
# y_clf -> 0 Setosa, 1 Versicolor, 2 Virginica (마찬가지로 iris.target에 이미 정해져 있음)

from sklearn.model_selection import train_test_split

X_clf = iris.data
y_clf = iris.target

X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(X_clf, y_clf, test_size=0.2, shuffle=True, random_state=12)
print(X_train_c.shape, y_train_c.shape)
print(X_test_c.shape, y_test_c.shape)

(120, 4) (120,)
(30, 4) (30,)


In [53]:
print ("==================================")
print (" ACCURACY OF OTHER ML CLASSIFIERS" )
print ("==================================")

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

 ACCURACY OF OTHER ML CLASSIFIERS


In [54]:
#Logistic Regression
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train_c, y_train_c)

pred_lr = clf_lr.predict(X_test_c)

print ("\n--- LogisticRegression Classifier ---")
print (accuracy_score(y_test_c, pred_lr))
print (confusion_matrix(y_test_c, pred_lr))


--- LogisticRegression Classifier ---
0.9666666666666667
[[12  0  0]
 [ 0  8  1]
 [ 0  0  9]]


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [55]:
#Decision Tree
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train_c, y_train_c)

pred_dt = clf_dt.predict(X_test_c)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test_c, pred_dt))
print (confusion_matrix(y_test_c, pred_dt))


--- Decision Tree Classifier ---
0.9666666666666667
[[12  0  0]
 [ 0  8  1]
 [ 0  0  9]]


In [56]:
#Random Forest
print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train_c, y_train_c)
pred = rf_clf.predict(X_test_c)
print(accuracy_score(y_test_c,pred))
print (confusion_matrix(y_test_c, pred))


--- Radom Forest ---
0.9666666666666667
[[12  0  0]
 [ 0  8  1]
 [ 0  0  9]]


In [57]:
#KNN
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train_c, y_train_c)

KNeighborsClassifier(n_neighbors=6)

In [58]:
from sklearn import metrics

y_pred = knn.predict(X_test_c)
print(accuracy_score(y_test_c, y_pred))

1.0


In [59]:
classes = {0:'setosa',1:'versicolor',2:'virginica'}

x_new = [[3,4,5,2], [5,4,2,2]]

y_predict = knn.predict(x_new)

print(classes[y_predict[0]])
print(classes[y_predict[1]])

versicolor
setosa


**// Regression //**

In [60]:
# X_reg -> Sepal Length, Sepal Width, Petal Length, Petal Width. (iris.data를 통해 이미 저장되어있음)
# y_reg -> 0 Setosa, 1 Versicolor, 2 Virginica (마찬가지로 iris.target에 이미 정해져 있음)

from sklearn.model_selection import train_test_split

X_reg = iris.data
y_reg = iris.target

X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(X_reg, y_reg, test_size=0.2, shuffle=True, random_state=12)
print(X_train_r.shape, y_train_r.shape)
print(X_test_r.shape, y_test_r.shape)

(120, 4) (120,)
(30, 4) (30,)


In [61]:
#Linear Regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

model = LinearRegression()
model.fit(X_train_r, y_train_r)
ly_preds = model.predict(X_test_r)

print('평균제곱근오차', mean_squared_error(ly_preds, y_test_r))

def mse_np(actual, predicted):
    return np.mean((np.array(actual) - np.array(predicted)) ** 2)

print('평균제곱근오차', mse_np(ly_preds, y_test_r))

def mse(actual, predicted):
    sum_square_error = sum((a - p) ** 2 for a, p in zip(actual, predicted))
    mean_square_error = sum_square_error / len(actual)
    return mean_square_error

print('평균제곱근오차', mse(ly_preds, y_test_r))

평균제곱근오차 0.05013739489661495
평균제곱근오차 0.05013739489661495
평균제곱근오차 0.05013739489661495


In [62]:
#Decision Tree
from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor()
model.fit(X_train_r, y_train_r)

from sklearn.metrics import mean_squared_error

dy_preds = model.predict(X_test_r)
print('평균제곱근오차', mean_squared_error(dy_preds, y_test_r))

평균제곱근오차 0.03333333333333333


In [63]:
#Random Forest
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train_r, y_train_r)

from sklearn.metrics import mean_squared_error

ry_preds = model.predict(X_test_r)
print('평균제곱근오차', mean_squared_error(ry_preds, y_test_r))

평균제곱근오차 0.04447666666666667


In [64]:
#KNN
from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor(n_neighbors=6)
knn.fit(X_train_r, y_train_r)

KNeighborsRegressor(n_neighbors=6)

In [65]:
y_pred = knn.predict(X_test_r)

from sklearn import metrics
y_pred = knn.predict(X_test_r)
print(mean_squared_error(y_test_r, y_pred))

0.02222222222222222
